# Theory

## Sarcoplasmic reticulum and the E-C coupling

The contractile function of skeletal muscle fibers depends on the collaboration of a multitude of specialized components and organelles within fibers to enable coordinated force production in response to signals from the central nervous system, i.e. the excitation-contraction (E-C) and relaxation coupling [@sandow_excitation-contraction_1952]. A central governor of the E-C and relaxation coupling in muscle cells is the sarcoplasmic reticulum (SR), a specialized component of the endoplasmic reticulum [@volpe_endoplasmic_1992]. The SR comprise a network of longitudinal tubules surrounding each myofibril [@porter_sarcoplasmic_1956; @porter_studies_1957]. These tubules regularly merge into terminal cisternae, located at the junctions between A and I bands of sarcomeres, forming a "triad junction" with two terminal cisternae positioned opposite each other around a transverse tubule membrane (t-tubule) [@franzini-armstrong_studies_1970]. This distinct structure and localization of the SR within the skeletal muscle fibers, coupled with its calcium ion (Ca^2+^) storing and release properties [@porter_studies_1957; @porter_sarcoplasmic_1956; @fleischer_localization_1985; @wuytack_molecular_2002], enable the SR to transduce the electrochemical signals of a action potential into the mechanical movement of the cross bridge cycle [@geeves_molecular_2005; @barone_organization_2015]. Herein, the SR Ca^2+^ handling are primarily carried out by two distinct SR proteins, i.e. the ryanodine receptors type 1 (RyR1) Ca^2+^ release channels, situated on the SR terminal cisternae, and the sarcoplasmic/endoplasmic reticulum Ca^2+^ ATPase (SERCA), situated on the longitudinal SR which transports Ca^2+^ from the cytosol back into the SR lumen [@dulhunty_excitationcontraction_2006]. These structural attributes of the SR are substantially different between skeletal muscle fiber types, wherein type II fibers roughly contain twice the volume and area of SR terminal cisternae, about four to six times higher RyR1 content and showcase roughly three times higher SR Ca^2+^ release than type I fibers [@eisenberg_discrimination_1976; @ruegg_calcium_1986; @baylor_sarcoplasmic_2003; @margreth_ratio_1993; @delbono_sarcoplasmic_1996]. Moreover, SERCA exist in two isoforms: SERCA1 in type II fibers and SERCA2 in type I fibers [@lytton_functional_1992], with a significantly higher density observed in type II fibers compared to type I fibers  [@everts_quantitative_1989]. 

The remainder of this theory part will focus on the SR and its role in the E-C relaxation coupling, as well as addressing how the functional capacity of the SR is of importance for muscular fatigue and subsequently, important for general health and performance. Furthermore, the theoretical basis underlying how training adaptations in the SR Ca^2+^ handling properties *per se* may induce a significant effect on muscular function will be addressed, before presenting the current knowledge, together with knowledge gaps, of such adaptations.

### The E-C and relaxation coupling

Voluntary muscle contractions is initiated in the brain by the genesis of action potentials which is transmitted via sequential electrical and chemical events through the spinal cord, motor nerve and neuromuscular junction to the muscle fiber. Depolarization of the muscle fiber triggers conformational changes to the dihydropyridine receptor (DHPR) [@schneider_voltage_1973], situated on the t-tubule within the triad junction, and the subsequent opening of the RyR1 Ca^2+^ release channels, by a mechanical interaction of DHPR and RyR1 [@dulhunty_excitationcontraction_2006; @rios_calcium-induced_2018; @tanabe_regions_1990]. The following SR Ca^2+^ release through RyR1 leads to a significant increase in the concentration of free Ca^2+^ in the cytosol of muscle fibers ([Ca^2+^]~i~), typically by 10-20 fold [@bruton_mitochondrial_2003; @ingalls_intracellular_1999]. Ca^2+^ within the cytosol bind to troponin C, triggering the movement of tropomyosin, thereby facilitating the cycling of cross-bridges, ultimately leading to the development of force [@geeves_molecular_2005; @ashley_ca_1991]. Concomitantly, Ca^2+^ are continuously re-sequestered back into the SR by SERCA, utilizes the energy generated by adenosine triphosphate (ATP) hydrolysis to shuttle two Ca^2+^ ions from the cytosol into the SR lumen, while simultaneously transporting two protons from the SR lumen to the cytosol in exchange [@everts_quantitative_1989; @yu_h_1993], causing muscle fiber relaxation as [Ca^2+^]~i~ declines.


## SR Ca^2+^ handling in fatigue

The contractile function of skeletal muscle fibers declines during intense or prolonged physical exercise, i.e., fatigue develops [@hill_physiological_1925; @mosso_fatigue_1904]. A fundamental principle in exercise physiology is that energy is essential for performing work [@bassett_limiting_2000]. Accordingly, through repetitive muscle contraction work, the energy demands within the working muscle fibers are heightened, and hence, necessitating efficient ATP resynthesis to match the substantially increased ATPase activity, primarily by molecular motors, such as actomyosin cross-bridges, the SERCA, and to a lesser extent, the sarcolemmal Na^+^-K^+^-pumps [@matheson_skeletal_1991]. Ensuring adequate ATP supply to these proteins is crucial for preserving normal cellular function and integrity during prolonged or intense physical exercise, as ATP depletion will lead to detrimental outcomes, including the persistence of noncycling cross-bridges and the onset of rigor mortis, impaired SR Ca^2+^ pumping resulting in uncontrolled elevation of [Ca^2+^]~i~, and compromised maintenance of Na^+^ and K^+^ gradients across the sarcolemma resulting to impaired action potential conductance and eventual loss of muscle fiber excitability [@cheng_molecular_2018]. Evidently, mechanisms aimed at averting these deleterious effects of ATP depletion are present within the muscle fibers and includes; efficient metabolic pathways for ATP resynthesis and fatiguing mechanisms designed to reduce muscular ATP consumption. Accordingly, slow-twitch type 1 muscle fibers, characterized by a slower ATP consumption rate and a greater aerobic capacity, typically exhibit higher resistance to fatigue compared to fast-twitch type 2 muscle fibers [@bruton_effects_2006; @lytton_functional_1992; @everts_quantitative_1989-1; @essen_metabolic_1975]. 

Each link in the inherent chain of events of voluntary contractions could, either alone or in combination, be the cause of muscle fatigue. Yet, a substantial part of the exercise-induced fatigue development is related to impairments in the SR Ca^2+^ handling associated steps of the E-C and relaxation coupling [@bigland-ritchie_fatigue_1986; @baker_intracellular_1993; @byrd_effects_1989; @favero_prolonged_1993; @hostrup__2014; @li_effects_2002; @ortenblad_role_2011]. In which, the underlying fatiguing mechanisms involves a decrease in the rate of SR Ca^2+^ release, reduced maximal Ca^2+^-activated force production, reduced Ca^2+^ sensitivity, as well as reduced Ca^2+^ re-sequestering rates, with the significance of each of these factors varying according to the pattern and duration of muscle activation [@allen_skeletal_2008; @westerblad_changes_1991]. Inhibiting SR Ca^2+^ release is one of the most efficient strategies to decrease energy expenditure in contracting muscle fibers, as it reduces the number of ATP-consuming cross-bridge cycles and diminishing the requirement for ATP-dependent SR Ca^2+^ reuptake by SERCA [@cheng_molecular_2018]. During exercise, SR Ca^2+^ release can be impaired due to numerous mechanisms, and the most prominent seem to be P~i~ accumulation [@fryer_effects_1995; @westerblad_mechanisms_1996], reduced ATP [@dutka_effect_2004] and glycogen depletion [@nielsen_subcellular_2014; @ortenblad_role_2011]. Additionally, reduced SR Ca^2+^ uptake rates and subsequent slowing of muscle fiber relaxation can impair performance during dynamic exercise involving rapidly alternating movements [@allen_muscle_1995]. This impairment is influenced by substrate availability and levels of lactate, adenosine diphosphate (ADP), P~i~, Mg^2+^, and pH, which have been shown to alter the uptake rate during exercise [@stienen_uptake_1993; @westerblad_mechanisms_1996; @westerblad_relation_1988]. Thus, the functional capabilities of SR Ca^2+^ handling properties may be of importance attenuating fatigue development.


## Muscle fatigue - health and performance

### General health

One facet of physical health encompasses the musculoskeletal system, comprising three key elements: muscular strength, endurance, and flexibility [@kell_musculoskeletal_2001]. Herein, the term muscular endurance is used to reflect the capacity of muscles to sustain repeated contractions against a load over an extended duration. Higher levels of musculoskeletal fitness are in turn associated with numerous health benefits, e.g., reduced coronary risk factors [@kraus_effects_2002; @durstine_blood_2001; @kelly_cortisol_1998], heightened bone mineral density [@berard_meta-analysis_1997], improved glucose tolerance [@ramachandran_indian_2006; @pan_effects_1997], and greater success in completion of activities of daily living [@hunter_effects_2004]. Moreover, muscle fatigue is a very common side effect, and a nuisance for disease patients, in diseases like chronic obstructive pulmonary disease [@breslin_perception_1998], sarcopenia [@patino-hernandez_association_2017], cancer [@morrow_fatigue_2002; @ryan_mechanisms_2007], obesity [@resnick_cross-sectional_2006; @vgontzas_sleep_2000], and chronic fatigue syndrome [@kent-braun_central_1993]. Hence, the skeletal muscle represents a crucial focal point for interventions aimed at promoting health throughout the entire lifespan, as well as improving a pleura of pathophysiological conditions [@wolfe_underappreciated_2006-1]. Yet, there is a notable gap in understanding the health benefits associated with training-induced improvements in muscle fatigue, and herein, the role of SR Ca^2+^ handling properties.     


### Endurance performance

High rates of oxidative metabolism are required in order to sustain high absolute workloads during endurance sports, wherein the primary determining factors of endurance performance have been suggested to include the maximal rate of oxygen consumption (VO~2max~) and fractional utilization of VO~2max~ at lactate threshold, along with exercise economy [@joyner_endurance_2008]. These parameters are typically assessed in well-rested individuals and have traditionally been regarded as static measurements. However, recent research indicates that these physiological factors may undergo shifts in response to prolonged exercise [@clark_effects_2018; @clark_dynamics_2019], highlighting the need to integrate this dynamic aspect into the endurance performance model. Consequently, there is increasing recognition of durability, which refers to the time of onset and magnitude of deterioration in physiological-profiling characteristics during prolonged exercise, as a significant limiting factor in endurance performance [@maunder_importance_2021]. In contrast to the respective determinants of endurance performance, much less is know about the physiological determinants of durability, albeit that it is intrinsically connected to muscular fatigue [@matomaki_durability_2023], and thus, also SR Ca^2+^ handling properties. 


## Exercise training and SR Ca^2+^ handling

Over time, increasing the contractile demands placed on skeletal muscles during physical exercise will typically result in adaptations that improve functionality and performance towards the characteristics of the exercising stimulus [@bogdanis_effects_2012]. Accordingly, a period of endurance training will improve the ability of skeletal muscles to sustain a given workload for a longer period of time, through adaptations facilitating resilience to muscular fatigue. A salient response to endurance training aimed at enhancing resilience to muscular fatigue is an increase in the physiological capacity of ATP production, e.g. increased O~2~ delivery to exercising muscles through expanded blood volume, an increased stroke volume, and greater quantity of hemoglobin [@lundby_biology_2017; @lundby_did_2019], as well as peripheral adaptations, such as increased mitochondrial content and improved mitochondrial functions [@granata_training-induced_2018], increased capillarization surrounding the muscle fibers [@hoier_exerciseinduced_2014], and improved muscle glycogen availability [@gejl_local_2017]. However, much less is known about the possible adaptations at the level of the E-C and relaxation coupling and the factors underlying SR Ca^2+^ handling properties, i.e. SR Ca^2+^ uptake and release, SERCA ATPase activity, and SR protein contents (SERCA or RYR1). 

The principal of symmorphosis posits that all components in a biological system is quantitatively coupled to functional demands and no singular parameter encompasses unnecessary surplus capacity [@taylor_design_1981; @weibel_concept_1991]. Accordingly, given the known link between impaired SR Ca^2+^ handling and muscular fatigue, it may be expected that the quantitative attributes and the functional capacity of the SR Ca^2^ handling properties are inherently coupled to the functional demands of the biological system that is muscular fatigue. Thus, it might be anticipated that endurance training would reduce the SR impairment following a given training-load through adaptations in the SR Ca^2+^ handling properties. 


## Methods to study SR Ca^2+^ handling in skeletal muscle

Methods for analyzing SR Ca^2+^ handling are confined to *in vitro* settings, involving techniques such as muscle biopsy from whole muscle [@bergstrom_percutaneous_1975; @bergstrom_diet_1967] and dissection of single fibers from whole muscles [@lannergren_temperature_1987; @allen_skeletal_2008]. Intact single fiber dissection can be performed on animals and offer a robust approach for investigating muscle fiber force production during acute exercise along with fluorometric analysis of [Ca^2+^]~i~. In addition, single fibers can be mechanically or chemically skinned, which allows for controlled analysis of the functionality of each of the steps in the E-C and relaxation coupling [@lamb_measurement_2018; @wood_human_1975]. Skinned muscle fibers can be obtained from human muscle biopsies [@widrick_force-velocity-power_1998; @malisoux_calcium_2006]. Single fiber techniques are, however, best suited for investigation force and Ca^2+^ handling during acute exercise of the muscle fiber, and not for investigation of "chronic" training adaptations in response to exercise training.

Chronic training adaptations in SR Ca^2+^ handling properties can either be studied through functional or quantitative changes in the specific SR Ca^2+^ handling proteins, i.e. RyR1, SERCA1, SERCA2 and DHPR, or by directly measuring the rate of SR Ca^2+^ release and uptake. Analysis of function and content of SR proteins can be done on homogenized muscle tissue and includes analysis of SR protein content and concentration using immunoblotting [@ploug_glucose_1993], determination of the total number of 3H-ouabain binding sites [@lunde_ryanodine_1997; @norgaard_method_1984] and measurement of the Ca^2+^-dependent steady state phosphorylation from ATP [@everts_quantitative_1989-1], as well as analysis of SERCA activity using spectrophotometric techniques [@simonides_assay_1990]. However, potential changes in quantity and function of SR proteins do not necessarily reflect a 1:1 change in the total functionality of SR Ca^2+^ handling. Intriguingly, SR vesicles can be isolated from crude muscle homogenate, enabling the determination of rate of SR Ca^2+^ release and uptake using fluorometric techniques [@ruell_measurement_1995]. In principle, this method can be used to study how alterations in metabolites affect SR Ca^2+^ handling or, by using standard conditions, how SR Ca^2+^ handling properties has been changed by the fatigue development or by a period of exercise training, assuming that the change is unaffected by isolation [@ruell_measurement_1995]. However, investigations focusing on isolated cellular components can be highly productive in elucidating mechanisms but often lack the capacity to illustrate physiological significance. Additionally, these methods face challenges due to muscle tissue containing various fiber types with distinct properties, leading to issues with sample representativeness and potential misinterpretation from spatial and/or temporal averaging.

## Knowledge gap and research aims

To date, only a few studies have previously investigated the effect of exercise training on SR Ca^2+^ handling properties. Wherein, a period of resistance training has been demonstrated to enhance SERCA activity and SR vesicle Ca^2+^ uptake in elderly women but not in young women [@hunter_human_1999]. Conversely, in young untrained males, resistance training has been associated with enhanced SERCA activity [@green_exerciseinduced_1998]. Moreover, enhancements in SR vesicle Ca^2+^ release and uptake in young, trained men following resistance training has been demonstrated, albeit without alterations in SERCA, RYR1, and DHPR contents [@jessen__2021]. Sprint training has been found to decrease SERCA activity while enhancing SR vesicle Ca^2+^ uptake in sedentary adults [@harmer_effects_2014]. Furthermore, sprint training in moderately trained men has led to increased SR vesicle Ca^2+^ release and SERCA and RYR1 contents, with no alterations observed in SR vesicle Ca^2+^ uptake and SERCA activity [@ortenblad_enhanced_2000]. Collectively, both resistance and high-intensity sprint training appear to serve as robust stimuli for quantitative improvements in SR Ca^2+^ handling properties.

However, previous research into the effects of endurance training on SR Ca^2+^ handling have yielded somewhat inconsistent findings. For instance, in rats, aerobic exercise results in reduced SERCA content and activity [@green_exercise-induced_1984; @kim_effect_1981], due to a fast-to-slow fiber transition. Conversely, studies in trained men have shown no alterations in SERCA content and fiber type distribution following six weeks of high-intensity endurance training [@madsen_effects_1994]. However, ten weeks of prolonged submaximal endurance training has been associated with reductions in SERCA1 content, while SERCA2 content remained unchanged, alongside reductions in SERCA activity and SR vesicle Ca^2+^ release and uptake [@green_adaptations_2003]. Additionally, four weeks of high-intensity endurance training have been shown to increase SR vesicle Ca^2+^ release, but SR Ca^2+^ vesicle uptake remained unchanged in highly trained triathletes and cyclist [@gejl_effects_2020]. 

This discrepancy in SR Ca^2+^ handling responses following endurance training between training regimes (moderate vs high-intensity) and participant characteristics (old vs young and trained vs untrained) is poorly understood. And, whether SR Ca^2+^ release and uptake rates are affected by high-intensity endurance training in untrained adults remains to be elucidated. Furthermore, there is limited understanding of how training-induced changes in SR Ca^2+^ handling impact muscular performance and overall health. In addition, to the best of my knowledge, only one study have previously investigated the interaction of sex on SR Ca^2+^ handling properties, and found that total SERCA activity was lower in the females compared to the males, but that SR vesicle Ca^2+^ uptake did not differ between sexes [@harmer_effects_2014]. This sex difference in SERCA activity were hypothesized to be due to discrepancy in fiber type distribution [@harmer_effects_2014]. However, it remains unclear if differences in SR Ca^2+^ release exist between sexes, and further investigation is needed to ascertain whether potential variations in SR Ca^2+^ release and uptake are attributable to differences in fiber type distribution among sexes.

Therefore, the present study was undertaken to further elucidate the effect of endurance training on SR Ca^2+^ handling properties and subsequent implications for muscular function and performance, as well as sex interactions on SR Ca^2+^ handling properties and fiber type distribution at baseline and in response to training. The primary aims of this study was to (1) investigate the effects of an eight-week endurance training intervention in untrained adult individuals on SR Ca^2+^ release and uptake rates, and (2), examine how the possible changes in SR Ca^2+^ release and uptake rates corresponds with changes in cycling performance and durability. Secondarily, the study aimed to (1) investigate possible sex differences in SR Ca^2+^ release and uptake and MHC distribution at baseline and in response to the training intervention, and (2), investigate the importance of average percentage of VO~2max~ during interval-sessions on training responses in SR Ca^2+^ handling properties. 
