# Introduction

The contractile function of skeletal muscle fibers relies on a complex interplay of intrinsic mechanical, electrochemical, and metabolic properties and processes, denoted as the excitation-contraction (E-C) and relaxation coupling [@sandow_excitation-contraction_1952]. Briefly, depolarization of the muscle fiber triggers the opening of calcium ion (Ca^2+^) release channels (ryanodine receptor, (RyR1)) on the sarcoplasmic reticulum (SR), leading to a significant increase in the concentration of free Ca^2+^ in the cytosol of muscle fibers ([Ca^2+^]~i~), typically by 10-20 fold [@bruton_mitochondrial_2003; @ingalls_intracellular_1999]. This elevated [Ca^2+^]~i~ subsequently initiates the cross-bridge cycle, inducing muscle fiber contractions [@geeves_molecular_2005]. Simultaneously, Ca^2+^ are continuously re-sequestered back into the SR by another SR membrane protein, the sarcoplasmic/endoplasmic reticulum Ca^2+^ ATPase (SERCA), causing muscle fiber relaxation when [Ca^2+^]~i~ declines. 

Through repetitive muscle contraction work, these SR Ca^2+^ handling properties will be disturbed [@bigland-ritchie_fatigue_1986; @baker_intracellular_1993; @byrd_effects_1989; @favero_prolonged_1993; @hostrup__2014; @li_effects_2002; @ortenblad_role_2011]. As a consequence, this will result in a progressive loss of force generating capacity, referred to as muscular fatigue [@hill_physiological_1925; @mosso_fatigue_1904]. The underlying fatiguing mechanisms in SR Ca^2+^ handling involves a decline in the rate of SR Ca^2+^ release, along with, in certain cases, diminished Ca^2+^ re-sequestering rates [@allen_skeletal_2008]. Higher levels of musculoskeletal fitness, which includes the ability of skeletal muscles to sustain repeated contractions against a external load for an extended period of time [@kell_musculoskeletal_2001], are associated with both numerous health benefits, e.g., reduced coronary risk factors [@kraus_effects_2002; @durstine_blood_2001; @kelly_cortisol_1998], improved glucose tolerance [@ramachandran_indian_2006; @pan_effects_1997], and greater success in completion of activities of daily living [@hunter_effects_2004], as well as superior endurance performance [@maunder_importance_2021]. In addition, muscle fatigue is a very common side effect, and a nuisance for disease patients, in chronic obstructive pulmonary disease [@breslin_perception_1998], sarcopenia [@patino-hernandez_association_2017], cancer [@morrow_fatigue_2002; @ryan_mechanisms_2007], obesity [@resnick_cross-sectional_2006; @vgontzas_sleep_2000], and chronic fatigue syndrome [@kent-braun_central_1993] Yet, there is a notable gap in understanding the health and performance benefits associated with training-induced improvements in SR Ca^2+^ handling properties.     

Over time, increasing the contractile demands placed on skeletal muscles during physical exercise will typically result in adaptations that improve functionality and performance towards the characteristics of the exercising stimulus [@bogdanis_effects_2012]. Accordingly, a period of endurance training will improve the ability of skeletal muscles to sustain a given workload for a longer period of time, through adaptations facilitating resilience to muscular fatigue. In this respect, a salient response to endurance training is an increase in the physiological capacity of ATP production, e.g. increased O~2~ delivery to exercising muscles through expanded blood volume, an increased stroke volume, and greater quantity of hemoglobin, [@lundby_biology_2017; @lundby_did_2019], as well as peripheral adaptations, such as increased mitochondrial content and improved mitochondrial functions [@granata_training-induced_2018], increased capillarization surrounding the muscle fibers [@hoier_exerciseinduced_2014], and improved muscle glycogen availability [@gejl_local_2017]. However, much less is known about the possible adaptations at the level of the E-C and relaxation coupling, and herein the SR Ca^2+^ handling properties *per se*. The principal of symmorphosis posits that all components in a biological system, such as for muscular fatigue, is quantitatively coupled to functional demands [@taylor_design_1981; @weibel_concept_1991]. Thus, given the known link between impaired SR Ca^2+^ handling and muscular fatigue, it might be anticipated that endurance training would reduce the SR impairment following a given training-load through adaptations in the SR Ca^2+^ handling properties. 

To date, previous studies investigating the effect of endurance exercise training on SR Ca^2+^ handling properties have shown rather inconsistent results. For instance, studies investigating content and function of SR proteins, have shown that aerobic exercise results in reduced SERCA content and activity in rats [@green_exercise-induced_1984; @kim_effect_1981]. In humans, SERCA content have been shown to remain unaltered following high-intensity endurance training [@madsen_effects_1994], however, moderate-intensity endurance training has been associated with reductions in SERCA1 content and total SERCA activity, while SERCA2 content remained unchanged [@green_adaptations_2003].

Intriguingly, SR vesicles can be isolated in muscle homogenate, and the functional capacity of SR Ca^2+^ uptake and release can be measured directly [@ruell_measurement_1995]. Using this technique, sprint training in sedentary and moderately trained adults, have indicated no significant alteration in SR Ca^2+^ uptake [@harmer_effects_2014; @ortenblad_enhanced_2000], whereas SR Ca^2+^ release has been observed to increase by 9% [@ortenblad_enhanced_2000]. Two studies has previously investigated the effect of endurance training on SR Ca^2+^ release and uptake. Whereby, moderate-intensity endurance training have been shown to reduce SR Ca^2+^ release and uptake in untrained men by 26% and 18%, respectively [@green_adaptations_2003]. Conversely, high-intensity endurance training have been shown to increase SR Ca^2+^ release by 10%, while SR Ca^2+^ uptake remained unchanged in highly trained endurance athletes [@gejl_effects_2020]. This discrepancy in SR Ca^2+^ handling responses following endurance training between training regimes (moderate vs high-intensity) and participant characteristics (trained vs untrained) is poorly understood. And, whether SR Ca^2+^ release and uptake rates are affected by high-intensity endurance training in untrained adults remains to be elucidated. In addition, to the best of my knowledge, only one study have previously investigated the interaction of sex on SR Ca^2+^ handling properties, and found that total SERCA activity was lower in females compared to males, but that SR vesicle Ca^2+^ uptake did not differ between sexes [@harmer_effects_2014]. This sex difference in SERCA activity were hypothesized to be due to discrepancy in fiber type distribution [@harmer_effects_2014]. However, it remains unclear if differences in SR Ca^2+^ release exist between sexes, and further investigation is needed to ascertain whether potential variations in SR Ca^2+^ release and uptake are attributable to differences in fiber type distribution among sexes.


Therefore, the primary aims of this study was to (1) investigate the effects of an eight-week endurance training intervention in untrained adult individuals on SR Ca^2+^ release and uptake rates, and (2), examine how the possible changes in SR Ca^2+^ release and uptake rates corresponds with changes in cycling performance and durability. Secondarily, the study aimed to (1) investigate possible sex differences in SR Ca^2+^ release and uptake and myosin heavy chain (MHC) distribution at baseline and in response to the training intervention, and (2), investigate the importance of average percentage of maximal oxygen consumption (VO~2max~) during interval-sessions on training responses in SR Ca^2+^ handling properties.
