# Discussion

The present findings yield novel insights into the effects of endurance training on SR Ca^2+^ handling properties and support the idea of training adaptations in SR Ca^2+^ handling properties to counteract muscle fatigue and thus enhance muscular function and performance. The present study demonstrate that eight weeks of endurance training enhances SR Ca^2+^ release and uptake in the leg muscles of previously untrained adults. Moreover, as the first study to investigate sex differences in SR Ca^2+^ release, the present findings showcase that females and males does not differ in SR Ca^2+^ release at baseline or in response to training. However, females displayed lower uptake~600nM~ at baseline, and larger enhancement in response to training.

Contrary to prior beliefs that enhanced SR Ca^2+^ release and uptake would subsequently improve cycling performance, the present findings did not demonstrate such relationships. SR Ca^2+^ release showed no association with cycling performance, and a negative relationship between change in uptake~tau~ and change in cycling performance was observed. In contrast, uptake~600nM~ and uptake~200nM~ at baseline, were positively associated with higher baseline levels of cycling performance.      

## Effect of endurance training on SR Ca^2+^ release

The observed increase of 7.3% in SR Ca^2+^ release rate is in accordance with previously reported training responses to resistance, sprint and high-intensity endurance training, performed on trained, moderately-trained, and highly-trained individuals [@jessen__2021; @ortenblad_enhanced_2000; @gejl_effects_2020]. The present finding expands upon this knowledge by showcasing that eight weeks of endurance training enhances SR Ca^2+^ release in thirty-seven previously untrained adults. However, this is in contrast to a previous result on prolonged submaximal endurance training, in which, SR Ca^2+^ release was reduced following the training period [@green_adaptations_2003]. Considering that @gejl_effects_2020 and @ortenblad_enhanced_2000 reported slightly larger improvements in SR Ca^2+^ release (9% and 10%, respectively) compared to the 7.3% observed in the present study, following just four and five weeks of training that included intermittent all-out sprint training, high-intensity training may be essential for inducing enhancements in SR Ca^2+^ release. Accordingly, the discrepancy between the present result and the reduction in SR Ca^2+^ release  following prolonged submaximal endurance training [@green_adaptations_2003], could be a consequence of the current endurance training protocol, which included some high-intensity and maximal effort exercises. Intriguingly, in the present study, an inverse relationship between exercise intensity, i.e. percent of VO~2max~ during interval sessions, and improvements in SR Ca^2+^ release was observed. Thus, the importance of exercising at high intensities to elicit enhancements in SR Ca^2+^ release may be questioned. However, the relevance of this relationship remains questionable considering that VO~2~ was measured during one of the three interval types (i.e., 4x8min session) and only at two of the twenty-four total interval sessions.

Since the analysis of the rate by which the SR releases Ca^2+^ are done *in vitro* under apparently constant conditions, and under no influence from the intracellular milieu nor under physiological voltage sensor control, the observed increase in SR Ca^2+^ release rate has to be due to either permanent changes in the content of RyR1 in the muscle tissue and/or modulation of the RyR1 opening probability. Consecutively, elevated content of RyR1 in the muscle tissue could be due to one or a combination of the following three hypotheses: modifications in fiber type distribution (specifically, from MHC-I to MHC-II), increased density of RYR1 and/or elevated SR content *per se* within the existing fiber types. In order to differentiate between some of these possibilities, the relative proportion of MHC isoforms was measured in the present study, which during the training period shifted towards a higher relative proportion of MHC-II. Considering the substantial quantitative differences in structural attributes of the SR between the two fiber types, wherein type II fibers roughly contain twice the volume and area of SR terminal cisternae, about four to six times higher RyR1 content and showcase roughly three times higher SR Ca^2+^ release than type I fibers [@eisenberg_discrimination_1976; @ruegg_calcium_1986; @baylor_sarcoplasmic_2003; @margreth_ratio_1993; @delbono_sarcoplasmic_1996], SR Ca^2+^ release rate might have been enhanced due to the increase in the relative proportion of MHC-II. However, the observed change in relative proportion of MHC-II was not associated with changes in SR Ca^2+^ release, implying that the enhancement in SR Ca^2+^ release was caused by alternative mechanisms. This assertion was further supported by the additional absence of an association between the initial MHC-II distributions and the initial rates of SR Ca^2+^ release, and consequently, raising doubt on the significance of MHC distribution alone on SR Ca^2+^ release rates. 

The relative importance of the other mechanisms that might elevate RyR1 content, i.e. enhanced RyR1 density and enhanced SR content, or the importance of alterations in RYR1 opening time and/or conductance, can only be speculated. @ortenblad_enhanced_2000 concluded that the observed increase in SR Ca^2+^ release after five weeks of intermittent 20 x 10-s all-out sprints were associated with increased RyR1 content as a consequence of an overall expansion of the SR volume, however, whether this is translatable to the present situation is unclear. In theory, the observed increase in SR Ca^2+^ release might also be due alterations in RyR1 opening probability, through alterations in the structure or gating dynamics of RyR1. The significance of this hypothesis remains speculative as previous studies have not explored the training effects on this aspect. Nevertheless, acute high-intensity training has been shown to induce structural alterations of RyR1 (i.e., fragmentation) in recreationally active individuals, with subsequent reductions in SR Ca^2+^ release and increases in SR Ca^2+^ leak, which persisted 24 hours post-training [@place_ryanodine_2015]. However, considering that muscle biopsies were sampled before endurance testing at pretest and more than 48 hours following the last training session, as well as no observed alterations in SR Ca^2+^ leak in the present study, it is unlikely that this effect influenced the observed increase in SR Ca^2+^ release rate; however, if it did, it would likely result in an underestimation of the effect.


## Effect of endurance training on SR Ca^2+^ uptake

To my knowledge, the present study is the first to demonstrate that SR Ca^2+^ uptake rates are enhanced following a period of endurance training, evident by the observed 13.2% and 8.9% increase in uptake~tau~ and uptake~600nM~, respectively. In previous studies, SR Ca^2+^ uptake has been shown to remain unaltered following high-intensity endurance training [@gejl_effects_2020] and sprint training [@ortenblad_enhanced_2000], as well as been reduced following moderate-intensity endurance training [@green_adaptations_2003]. However, in the latter study @green_adaptations_2003 observed reductions in SR Ca^2+^ uptake rates at [Ca^2+^]~free~ levels between 1000 nM and 2000 nM, which correspond to supra-physiological levels, and SR Ca^2+^ uptake rates closer to physiological levels (i.e., <1000 nM) remained unaltered, and thus, questioning the physiological relevance of these results. 

Since the measurements on the rate by which SR re-sequesters Ca^2+^ are done *in vitro* under constant conditions, potential changes in SR Ca^2+^ uptake could arise from alterations in the number of active SERCA, SERCA hydrolysis rates and/or properties of the SERCA ATP binding site. None of the respective SR Ca^2+^ handling properties were measured in the present study, however, type II muscle fibers generally encompass four to six times higher SERCA activity and contents than MHC-I fibers [@eisenberg_discrimination_1976; @ruegg_calcium_1986]. Accordingly, the observed changes in SR Ca^2+^ uptake could be attributed to the observed increase in relative proportion of MHC-II. Yet, change in uptake~tau~ and uptake~600nM~ was not related to changes in the relative proportion of MHC-II, and neither was initial SR Ca^2+^ uptake rates and initial relative proportion of MHC-II related. Thus, SR Ca^2+^ uptake properties seem to a large degree to be uninfluenced by MHC distributions and the observed elevation in SR Ca^2+^ uptake may rather be due to alterations of the respective attributes within the muscle fibers irrespective of general fiber types. Additionally, and in contrast to what was observed on SR Ca^2+^ release, exercise intensity was not associated with changes in SR Ca^2+^ uptake.

In the present study, a positive relationship between changes in uptake~200nM~ and changes in the relative proportion of MHC-II was observed, however, the relevance of this relationship in regard to muscular performance might be questioned by the absence of an increase in uptake~200nM~ following the training intervention. Nevertheless, this relationship implicates that a increase in relative proportion of MHC-II improves the capacity of SR Ca^2+^ uptake at resting [Ca^2+^]~free~ levels.

## Sex differences in SR Ca^2+^ release and uptake

The present study is, to my knowledge, the first study to highlight that SR Ca^2+^ release is similar between sexes, and that the subsequent responses to exercise training does not differ between sexes. However, females showcased lower uptake~600nM~ at baseline, and larger enhancements in response to training in comparison to males, which is in contrast to results from a previous study showing no effect of sex on SR Ca^2+^ uptake [@harmer_effects_2014]. However, the same study did observe lower SERCA activity in females compared to males, which they proposed was due to known sex differences in fiber type composition [@simoneau_human_1989; @roepstorff_higher_2006] with subsequent fiber type differences in SERCA activity [@li_effects_2002]. However, despite a -7.3% difference in baseline values of relative proportion of MHC-II in females compared to males in the present study, the observed sex interaction in uptake~600nM~ was practically unchanged after accounting for MHC distribution in the same model. Suggesting that the observed difference is not explained by differences in MHC distribution between sexes at baseline. Moreover, the observed sex interaction on training response in uptake~600nM~ was not altered after accounting for MHC distribution in the same model, nor did the changes of relative proportion of MHC-II in response to training differ between sexes. Therefor, the observed sex differences in uptake~600nM~ may rather be due to differences in attributes within the muscle fibers irrespective of fiber types, i.e. content of active SERCA or SERCA hydrolysis rates and/or properties of the SERCA ATP binding site. 

## Implications of SR Ca^2+^ handling properties on performance and health

The present study demonstrated a robust increase in SR Ca^2+^ release and uptake rates following eight weeks of endurance training including twenty-four training sessions. This effect, in line with the principal of symmorphosis [@taylor_design_1981; @weibel_concept_1991], might be anticipated to enhance the muscle`s maximal exercise capacity. This idea is supported by the concomitant improvements in cycling performance (i.e., W~15min~, W~max~) along with improvements in VO~2max~ following the endurance training period. However, an inverse relationship between enhancements in uptake~tau~ and improvements in both W~15min~ and W~max~ was observed in the present study. The overall relevance of these relationships may be questioned by the rather poor model fit, evident by R^2^~adjusted~ values of 0.16 and 0.13, respectively. Previous studies have consistently highlighted acute deteriorations in SR Ca^2+^ handling as an important mechanism underlying the development of muscle fatigue, however, the impairment is primarily related to declining SR Ca^2+^ release [@li_effects_2002; @duhamel_manipulation_2006; @gejl_muscle_2014; @place_ryanodine_2015]. Hence, SR Ca^2+^ uptake might not be among the main limiting components in muscular fatigue, and thus, increasing SR Ca^2+^ uptake rate may therefore not be expected to improve resilience to muscular fatigue. This is supported by previous findings suggesting that SR Ca^2+^ uptake is less trainable in response to high-intensity endurance and high-intensity intermittent sprint training [@ortenblad_enhanced_2000; @gejl_effects_2020]. Interestingly, uptake~600nM~ and uptake~200nM~ at baseline were positively related to baseline values in W~15min~, W~max~ and VO~2max~, indicating that the mechanisms of SR Ca^2+^ uptake in regulating endurance performance might differ between initial performance and changes in performance.

The observed increase in SR Ca^2+^ release rate showed no associations with the observed improvements in W~15min~, W~max~ and VO~2max~, which is in accordance with previous findings [@ortenblad_enhanced_2000; @gejl_effects_2020]. However, it is also crucial to acknowledge that establishing significant correlations or regressions between two delta parameters (change scores) tend to require very large sample sizes or vary strong associations, i.e. doubles the variation for each parameter by introducing twice the sources of measurement error. Thus, considering that endurance performance is highly multifactorial with the main determinants being VO~2max~, fractional utilization of VO~2max~ at lactate threshold and exercise efficiency [@joyner_endurance_2008], it is probable that the influence of the SR Ca^2+^ release at the level of the E-C coupling, although positive, is mitigated when considering the overall body's response to endurance training, owing to numerous confounding factors that impact endurance performance. in addition, initial levels of SR Ca^2+^ release showed no relationship with W~15min~, W~max~ or VO~2max~, and thus, indicating that the magnitude by which SR Ca^2+^ release relates to endurance performance is relatively small.

The ability to maintain performance over time, i.e., durability, is also considered to be among the main limiting factors of endurance performance [@maunder_importance_2021]. Thus, and in consideration with the prior idea of training adaptations in SR Ca^2+^ handling properties to counteract muscle fatigue, a durability index was calculated as the percentage of W~15min~ in regard to W~max~. Improving the durability index may therefore reflect an improved ability to sustain high relative workloads in an already fatigued state. However, at the group level, the durability index did not change following the training period, nor was the change in SR Ca^2+^ release and uptake associated with changes in durability index. This might be explained by large variation in individual change scores of durability index, evident by the bigger range of 95% CI (Figure 3E), possibly due to inexperience of the participants in conducting cycling trials to exhaustion and by the introduction of measurement error in two separate tests.

Taken together, the observed improvement in SR Ca^2+^ release may have contributed to enhancements in muscular function and performance, due to improved resilience to muscular fatigue, which may have important implications for general health and performance. In contrast, the present findings suggest that SR Ca^2+^ uptake may be of less importance. Interestingly, enhanced contractile force in non-fatigued muscle in trained men have previously been associated with pharmacological-induced increases in SR Ca^2+^ release rate via β2-adrenergic stimulation [@hostrup__2014]. Thus, suggesting that in addition to the potential effects on resilience to muscle fatigue, enhanced SR Ca^2+^ release *per se* might also be associated with an increase in contractile function. 

## Methodological considerations

A significant limitation of ecological validity in the present study stems from the absence of a control group. As described previously (see section “Methods”), the present investigation of training responses in SR Ca^2+^ handling properties constituted a segment of a larger scientific project that tracked the same participants through two consecutive and identical training interventions aimed at examining intra- and interindividual variations in training responses. Nonetheless, a prior study on 5-week sprint training has shown that the control subjects exhibited no alterations in SR Ca^2+^ handling properties [@ortenblad_enhanced_2000]. If this could translate to the present setting can only be speculated. Additionally, analysis of SR Ca^2+^ release and uptake are limited to *in vitro* settings, which fail to capture interactions of the among various intracellular sites and conditions. Consequently, while changes in SR Ca^2+^ release and uptake after exercise training are evident under isolated *in vitro* conditions, it's imperative to evaluate the physiological significance of these changes for overall muscle function. This methodology hinges on the crucial assumption that the SR vesicle utilized for *in vitro* SR Ca^2+^ release and uptake measurements is functionally representative of *in vivo* muscle conditions.

## Conclusion

In conclusion, the present study demonstrates that the rate of SR Ca^2+^ release and uptake can be enhanced by eight weeks of endurance training in sedentary adults, which may have important implications for muscular performance and general health. Moreover, SR Ca^2+^ release does in general not differ between sexes, with the exception of females displaying lower rates of SR Ca^2+^ uptake prior to training, yet larger gains in response to training, possible due to mechanisms other than fiber type composition.    




