# Acknowlegdements {.unnumbered}

First and foremost, I would like to thank Knut Sindre Mølmen, Invill Odden and Carsten Lundby for all the responsibility I was given in the planning and conduction of this project. And a special thanks to Knut Sindre Mømlen and Ingvill Odden for your feedback and guidance during the writing process. Also, i would like to thank Niels Ørtenblad for facilitating an educational stay at the scientific laboratory of the University of Southern Denmark, Odense, and for your guidance during the writing process.

A big thank you to my co-master students Pia Julie Demler and Eirik Mølmshaug for excellent collaboration during the planning and conduction of this project, and during the data processing afterwards. Also, thank you Joar Hansen for your help with the hematological measurements in the laboratory. For help with interval-sessions and testing, thank you to our hardworking bachelor students Emma Riiber, Andrine Juvodden, Borghild Dalbø, Kristoffer Rogstadmoen, Eskil Eng Auestad, Andreas Braanes, Vebjørn Ekeli and Markus Andersen. 

I would also like to thank all the staff at the Section for Health and Exercise physiology along with fellow students for five great and educational years.

Finally, a big thank you to all our participants for excellent efforts during the project.